### ISSUE TITLE
Initialization error-Midjourney(discord_channel_id, discord_user_token)

### ISSUE THREAD

**Issue by playsimple-games-snehaa** [reise69/Midjourney-sdk#1]
When I try to run:
`midjourney = Midjourney(discord_channel_id, discord_user_token)`

it gives the belwo error:

> File <command-3076146499114284>, line 1
----> 1 midjourney = Midjourney(discord_channel_id, discord_user_token)
      3 prompt = "A teddy bear in Scotland, holding a French flag, with a Scottish landscape in the background, in a comic style"
      4 options = {
      5     "ar": "3:2",
      6     "v": "6.0",
      7 }

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-ec18902f-333e-4cde-9a8b-24586fce4f06/lib/python3.10/site-packages/midjourney_sdk_py/main.py:27, in Midjourney.__init__(self, channel_id, oauth_token)
     24 response = self.client.get(f'{self.API_URL}/channels/{self.channel_id}')
     25 data = response.json()
---> 27 self.guild_id = data['guild_id']
     29 response = self.client.get(f'{self.API_URL}/users/@me')
     30 data = response.json()

KeyError: 'guild_id'

Could someone please help with this error?

**Comment by reise69** [comment]
@playsimple-games-snehaa  

Hi there! I apologize for the delayed response.

The error you're experiencing occurs when the application can't properly connect to Discord using the provided credentials. This KeyError: 'guild_id' specifically indicates that the bot cannot access the Discord channel information, which is usually caused by either:

An invalid Discord token
An incorrect channel ID

Good news though! In the latest version of the library, I've added explicit error messages to help debug these connection issues. I recommend:

Updating to the latest version via pip:

```bash
pip install --upgrade midjourney-sdk-py
```

Double-checking your configuration by reviewing the setup instructions in the README.md file to ensure you're using:
        The correct Discord channel ID
        A valid Discord user token

If you're still experiencing issues after updating and verifying your configuration, please feel free to open a new issue with the error message from the latest version, which should provide more detailed information about what's going wrong.

Let me know if you need any further clarification!
